### PR TITLE
Clean

### PR DESCRIPTION
**Pull request by flagarde**
Supress old CI and related scripts

### CODE REVIEW

**Review by MCWertGaming — CHANGES_REQUESTED** [review]
Shouldn't we keep the integration testing, like the input test, also the basic prompt testing?

**Comment by flagarde** [comment]
If I understand correctly this is already done on the CI. I copied the file and renamed it examples.sh/ps1 I just removed the tests/* because this is executed by the ctest command. Please have a look and check  if I didn't make any mistake or misunderstood your comment. Plase have a look on `https://github.com/jupyter-xeus/cpp-terminal/actions/runs/3778090690/jobs/6422284782` `Test` and `Run example`

**Comment by MCWertGaming** [comment]
Hey @flagarde it's more about this https://github.com/jupyter-xeus/cpp-terminal/pull/210/files#diff-9ac46bb912c722259b7a921143fc1f2b52fe970b6fabddf2ac710b4c338b4540. @certik implemented some tests for the prompt input and I created a simple test for checking if the stdin reading works in a real environment. Would be nice if we keep that for now. If you have an Idea on how we can test those better, feel free to propose something!

**Comment by flagarde** [comment]
@MCWertGaming sorry but I still don't get it. I added a examples.sh that is mainly a copy-paste of tests.sh and it is executed during the new CI. 

```bash
#! /bin/bash

set -ex

./install/bin/examples/colors
./install/bin/examples/read_stdin

echo "testing stdin example"
if [[ $(echo test | ./install/bin/examples/read_stdin) != "Input from stdin: test" ]]; then
  echo "stdin example returned wrong input"
  exit 1
fi

echo "Expected to succeed:"
./install/bin/examples/colors < ./install/bin/examples/colors
echo "Expected to fail"
set +e
./install/bin/examples/keys < ./install/bin/examples/colors
if [[ $? != 0 ]]; then
  echo "Success"
else
  echo "Fail"
  exit 1
fi
set -e

echo
echo "Tests passed."
```

**Comment by MCWertGaming** [comment]
Oh sorry @flagarde I got it now. We can merge this then when the conflicts are resolved!

**Pull request closed without merging**
