### PR TITLE
alt and ctrl key fixes

### LINKED ISSUE #106: Fix alt heys
As we have discussed in #104 we have to fix issues with the alt keys. The current macro tends to cast values greater than 127 into a char type which results into a runtime error because a char can only hold values from 0 to 127.

### PR DESCRIPTION
**Pull request by MCWertGaming**
This PR fixes #106 but re-implements the ALT and CTRL key detection constant. This is a replacement for #80 and does an overall improvement for users.

### CODE REVIEW

**Review by certik — APPROVED** [review]
This is fine. I am still surprised that a function would not work, but we can do that later. I think this is good to merge.

**Comment by MCWertGaming** [comment]
yeah me too. But I'm also surprised that the macro worked... Is there something you would prefer to improve? I like it more this way as it's pretty similar to the other keys.

**Comment by MCWertGaming** [comment]
I'm merging this now. I'll move the conversation into the dedicated issue.

**Comment by certik** [comment]
Thanks for merging and thanks for your work!

**Pull request merged**
