### PR TITLE
Fix for undefined identifiers in platform.cpp

### PR DESCRIPTION
**Pull request by Milo46**
Fix for #163. Everything is provided in the issue description and commits are self-explanatory.

### CODE REVIEW

**Comment by MCWertGaming** [comment]
Hi! Thank you really much for this fix. CPP-Terminal is currently under development. The `platform.hpp` header was meant to only hold platform dependent code to keep it separate from the rest of the code base to make contributions more simple. The initial idea of it was to eliminate the errors caused by various macros in `windows.h` and others. I plan on implementing a conversion from the DWORDS to unsigned integers for the Terminal class to remove the header once for all so none of the definitions cause problems. Reviews in this repository take months though, so it's not yet implemented.

But yeah, Thank you for the fix! @certik I think that we can merge this.

**Review by MCWertGaming — APPROVED** [review]

**Comment by Milo46** [comment]
Thanks, if I find anything more I'll also try to fix/enhance it. And if somebody does come up with any better name for that file, please change it.

**Comment by MCWertGaming** [comment]
Sure, thank you again! I'll merge this if no comment by @certik was made until then.

**Comment by MCWertGaming** [comment]
Also the future of this Project is not really clear as the original author (certik) is barely maintaining it. Maybe create a fork with some additional fixes I need for my projects, like in #142 (mostly fixes for linux VGA console etc) and the required fixing of the `platform.hpp` header, the window class rework to make it agnostic with new terminals, while keeping down-wards compatility with old terminals that doesn't support multiple color codes and RGB colors (mostly macos).

But not sure when I get the required time for that. I'll keep maintaining this though of course.

**Comment by MCWertGaming** [comment]
I'll merge this then. Thank you for the fix!

**Comment by certik** [comment]
@MCWertGaming if you have time to maintain this, I would appreciate it. Thanks for merging this PR.

If possible, please don't make a fork just for your project, rather maintain this "community" version at `jupyter-xeus` and make sure it works for everybody. Let me know if you need any permissions at github.

**Comment by certik** [comment]
@Milo46 thanks for the fix! If you find anything else that breaks or want to help with development, please let us know!

**Comment by MCWertGaming** [comment]
> @MCWertGaming if you have time to maintain this, I would appreciate it. Thanks for merging this PR.
> 
> If possible, please don't make a fork just for your project, rather maintain this "community" version at `jupyter-xeus` and make sure it works for everybody. Let me know if you need any permissions at github.

Sure, I can maintain this for now. The idea for creating a separate fork resulted from the need for some projects I would like to start in some time that would involve real time rendering in the console, basically for animations and game behavior. I'm not sure yet how that will work out as, but nevertheless I'll port all fixes into cpp-terminal and might have to do some major changes to the window class, so when this is more likely unmaintained it would be impossible for me to create something in a reasonable time. But when we do it this way, that I simply take over the major code review part, I think that it'll be fine to simply contribute everything that I would consider as fitting and if needed make a separate library that uses cpp-terminal in the background and adds a simple interface for real time rendering. But if the changes are not too big, I'll try to add the rendering into cpp-terminal.

I have to implement the fixes anyway that are still pending, mostly the window class fixes like 24-bit colors.

But yeah, thank you @certik and I'll look into improving this project.

**Comment by certik** [comment]
Thanks @MCWertGaming. For big changes, please give me a chance to review, say 1 or 2 days, but if I can't do it, then just review yourself and merge.

**Comment by MCWertGaming** [comment]
Of course @certik.

**Pull request merged**
