### PR TITLE
Utf8

### LINKED ISSUE #259: Bug: cpp-terminal crashes if two utf8 are inserted simultaneously
I have a german keyboard with the 'ö' and 'ä' keys. In utf8 both are 2 bytes long. When I pressed them at the same time accidentally the cpp-terminal crashed. It crashed to such an extend that my terminal closed. I then tried the same not in my application but the kilo editor from the examples. The same thing happened and the kilo editor crashed as well and my terminal closed again. I tried it on the windows cmd terminal and power-shell - same result. But I think it has nothing to do with the terminal, since I can just enter both keys at the same time in the terminal command prompt without trouble .

### PR DESCRIPTION
**Pull request by flagarde**
@TobiasWallner @certik Fix #259 Please have a try in your platform.

### CODE REVIEW

**Comment by flagarde** [comment]
Sorry for the commits (clang-format autofix) and windows love to force some header inclusion order :(

**Comment by TobiasWallner** [comment]
I checked it out.
My issue #259, seems to be fixed and the terminal is no longer crashing on my machine.

**Comment by flagarde** [comment]
@certik Could you do a basic test om mac ? In linux it is fixed too :)

**Comment by TobiasWallner** [comment]
Enter not working in kilo editor

**Comment by flagarde** [comment]
@TobiasWallner ok thx for the test I will jave a look

**Comment by flagarde** [comment]
@TobiasWallner Should be fixed but I will have to dig more into it in the future

**Comment by TobiasWallner** [comment]
Hi, sry for the late reply, had lots of things to do.
Had a look inside your UTF8 just now and I cannot reproduce the strange error any more, where some characters would not be printed any more.
It seems like everything is working as it should.

**Comment by TobiasWallner** [comment]
Just to clear things up. Are you returning the key in utf8 or utf32?

**Comment by flagarde** [comment]
Keys are read/converted to utf8 (windows) store as codepoint (utf32) and send back to terminal as utf8

**Pull request merged**
