### PR TITLE
Make tests work on C++20, which uses a distinct type for utf8 chars.

### PR DESCRIPTION
**Pull request by mcourteaux**

### CODE REVIEW

**Comment by MCWertGaming** [comment]
Hey, thank you for the PR. I think additionally to the fix, we should look into covering C++20 in the CI as well. @flagarde

**Comment by flagarde** [comment]
@MCWertGaming Yes! Indeed I did this before but because of the test failing I supress the c++20. Maybe the library should try to have something transparent to the user to deal with this u8 problem between c++11 and c++20

**Comment by MCWertGaming** [comment]
Since this is just the unit testing, I'll merge it. We'll implement the testing in a new PR. Thank you really much for the work @mcourteaux!

**Comment by mcourteaux** [comment]
No problem. Thanks for the lib! :)

**Pull request merged**
