### PR TITLE
Use clang-format with pre-commit

### PR DESCRIPTION
**Pull request by flagarde**
This PR add pre-commit to run clang-format

Issues: #182

### CODE REVIEW

**Comment by MCWertGaming** [comment]
We should still check if clang-format was applied using a CI task. Can you add the pre-commit action? @flagarde

**Review by MCWertGaming — CHANGES_REQUESTED** [review]
The linting must be checked by the CI.

**Comment by MCWertGaming** [comment]
In other projects I'm using this https://github.com/github/super-linter. If pre-commit applies more than just clang-format, we might want to add a pre-commit specific CI task instead.

**Comment by flagarde** [comment]
see https://results.pre-commit.ci/run/github/444329333/1656480568.Q7IdB9SQQlKh1eKfxgJijw for example

**Comment by MCWertGaming** [comment]
Does pre-commit have any benefits over just applying clang-format? Super linter by github also tests for git leaks and other things additionally to linting the source code.

**Comment by MCWertGaming** [comment]
Oh, super linter does the same as well. Is the config necessary? Will add a workflow quickly

**Comment by flagarde** [comment]
Yes pre-commit can run many tools on CI and on computer https://github.com/yaodaq/YAODAQ/blob/main/.pre-commit-config.yaml etc .. You can even create yours

**Comment by flagarde** [comment]
you have even this if you want :) https://github.com/oxsecurity/megalinter with pre-commit I think

**Comment by flagarde** [comment]
Normally you even don't need the CI if the tools are installed inside the https://pre-commit.ci/ . You just have to give access to the app to the repo.. There is also auto PR for upgrade of the hooks. You need only a CI if the tools can't be installed by the hooks or are not present in pre-commit.ci

**Comment by MCWertGaming** [comment]
@certik hey, can you approve the request of adding pre-commit to the org? Until then we just use the CI task.

**Comment by MCWertGaming** [comment]
Automatically applying configuration can break the local branch. I wouldn't recommend that. Also feel free to add more hooks, seems pretty usefull.

**Review by MCWertGaming — APPROVED** [review]

**Comment by flagarde** [comment]
It's doesn't change automaticly but propose PR for example : https://github.com/yaodaq/YAODAQ/pull/21

**Comment by MCWertGaming** [comment]
Yeah, like dependabot.

**Comment by MCWertGaming** [comment]
Sadly I don't have high enough permissions on the organization to set up the pre-commit bot. So I'll merge this for now and look into reaching out to certik.

**Pull request merged**
