### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by flagarde**
This PR allows automatic doxygen generation on push (like this : https://flagarde.github.io/cpp-terminal). You need to setup some parameters on your side but it should work as soon you have configured github page correctly. PDF generation is still problematic because of unicode in the .cpp that LaTeX has problem to digest

### CODE REVIEW

**Comment by flagarde** [comment]
@certik @MCWertGaming If you merge this and setup github page this would be a nice addition for users and a nice way to promote the library IMHO.

**Review by MCWertGaming — APPROVED** [review]
This is really nice! I'll look into setting up github pages

**Comment by MCWertGaming** [comment]
Well apparently @certik has to enable it since I have just maintainer access to this repository. Can you help me out here Ondrej?

**Comment by certik** [comment]
@MCWertGaming tell me what you need and I'll enable it. The pages are can be served from a branch (which one?) or the new github pages can work via GitHub Actions also. Let me know which one you want.

**Comment by flagarde** [comment]
@certik Now, pages can be used without branch. I think you have to select via Github Actions and it should work. This is a snapshot of the config I used to obtain the pages :

Screenshot_20230516_163106

Then you could rerun the CI on this PR and it should works

**Comment by MCWertGaming** [comment]
Hey @certik it seems like the pages is still not working. Have you enabled it already?

**Comment by flagarde** [comment]
@MCWertGaming maybe the PR should be pushed with to take into account the changes?

**Comment by certik** [comment]
@MCWertGaming can you check with your new permissions?

**Comment by certik** [comment]
@MCWertGaming I see. I was waiting for you to tell me which pages option you want to enable. Based on @flagarde comment, I just enabled the GitHub Actions:

Screen Shot 2023-05-23 at 3 01 41 PM

@flagarde go ahead and try it.

**Comment by flagarde** [comment]
@MCWertGaming @MCWertGaming i don't have right to reload the CIs

**Comment by certik** [comment]
@flagarde I just added you as a Maintainer also. Can you check now?

**Comment by flagarde** [comment]
@MCWertGaming @certik https://jupyter-xeus.github.io/cpp-terminal/

**Pull request merged**
