### PR TITLE
added new styles

### PR DESCRIPTION
**Pull request by TobiasWallner**
I added a lot of new style settings in the enum found in style.hpp. I tried to add all releveant ones and added comments about their behaviour and implementation support.

### CODE REVIEW

**Comment by flagarde** [comment]
@TobiasWallner Nice, it's nice to have more feature like this :). Could you do a program to show all the diferents style. It could be use to check each terminal

**Comment by flagarde** [comment]
@TobiasWallner Yes I think in the examples fllder it would be nice

**Comment by TobiasWallner** [comment]
@flagarde May need help here. There is one failing test: "docs / 📚 Docs (pull_request)". I am not sure I think this already an open Issue, and you all are waiting for that to be merged, correct? Otherwise I need help on what to do to make this pass.

**Comment by flagarde** [comment]
@TobiasWallner I think this failing has been solved butbnotbin your PR we should not care about it

**Comment by TobiasWallner** [comment]
@flagarde Should I do or fix anything or can you do it. Or do you have any suggestions on how I can fix that?

**Comment by flagarde** [comment]
For the docs problem it's a doxygen problem... I have done a PR and issue report on the doxygen project. Maybe I can disable pdf generation for now.

**Pull request merged**
