### PR TITLE
CI: Add GitHub workflow tests

### PR DESCRIPTION
**Pull request by certik**

### CODE REVIEW

**Comment by certik** [comment]
Hm, looks like the GitHub Action is not running, have to figure out how to enable it.

**Comment by martinRenou** [comment]
@certik if you open the same PR from `certik:ci` to `certik:master` it will be triggered, that's useful just to check that the CI passes.

Once we merge it will be triggered for next PRs :)

**Comment by certik** [comment]
Great tip: https://github.com/certik/cpp-terminal/pull/1, I am working on getting it passing.

**Comment by certik** [comment]
I think I finally got it working. Once the CI passes, we can merge.

**Comment by certik** [comment]
Thanks @martinRenou !

**Pull request merged**
