### PR TITLE
Add versioning to cpp-terminal

### PR DESCRIPTION
**Pull request by MCWertGaming**
This adds the versioning of cpp-terminal requested in #74.

### CODE REVIEW

**Review by certik — APPROVED** [review]
I think that's fine.

**Comment by certik** [comment]
You have push access no. If the PR is approved, go ahead and merge it. Otherwise wait for it to be approved.

**Comment by certik** [comment]
This looks good. Isn't `version.h` or `config.h` a better name?

**Comment by MCWertGaming** [comment]
Yeah, I have renamed it to version.h.

**Review by certik — APPROVED** [review]
I think this looks great.

**Pull request merged**
