### PR TITLE
Simplify setOptions()

### PR DESCRIPTION
**Pull request by flagarde**
This PR simplify a bit the syntax to set options on terminal (check the examples). Mainly you don't need to use {} anymore

### CODE REVIEW

**Review by MCWertGaming — APPROVED** [review]
This looks fine too

**Comment by MCWertGaming** [comment]
Seems like the previous PR caused conflicts aaa, would you mind resolving them? @flagarde

**Comment by flagarde** [comment]
Ok i will try to fix this

**Comment by flagarde** [comment]
@MCWertGaming Conflicts should be fixed now :)

**Pull request merged**
