### PR TITLE
C++11

### PR DESCRIPTION
**Pull request by flagarde**
Allow to compile on c++11

### CODE REVIEW

**Comment by flagarde** [comment]
The failing one is due to doctest :(. Would you merge it too ? I would like to make some code modif and it should be nice to have all the ci set up.

I will try to desactivate the test compiling just for the gcc++4.7 on c++11 on other PR

**Comment by MCWertGaming** [comment]
Hey, sorry for the late reply. We can merge this without doctest if needed for now @flagarde. We'll merge when you did a rebase and fixed the CI. Thank you for looking into this!

**Comment by flagarde** [comment]
@MCWertGaming No problem. The CI are passing now :)

**Review by MCWertGaming — APPROVED** [review]
Looks really nice, thank you for the work!

**Pull request merged**
