### PR TITLE
24bit colors

### PR DESCRIPTION
**Pull request by MCWertGaming**
This pull-request adds `color24()`, a small addition to the `color()` function to use 24bit true color on supported terminals like discussed in #69.

### CODE REVIEW

**Review by certik — APPROVED** [review]
This looks good.

I wonder if there is a way to merge the two Window classes somehow, as I think there is a lot of repetitive code. But we can simply merge this, start using it, and then we can later see if there is a way to merge the two classes.

**Comment by MCWertGaming** [comment]
The current state:
image

**Comment by MCWertGaming** [comment]
> This looks good.
> 
> I wonder if there is a way to merge the two Window classes somehow, as I think there is a lot of repetitive code. But we can simply merge this, start using it, and then we can later see if there is a way to merge the two classes.

I have tried to merge both together at first, but it was really complicated to work with the code. Also using a union does not work, because you can't do `Color(w*h, {fg::reset})`. You need to do `Color[X].fg = fg::reset but` but to initialize id you need to do `Color.pushback(fg::reset)` which does not work at all, because the compiler doesn't know where to put the value (it has to go into Color.fg) and you can just either use the vector as an vector object or as an union object to access the union's members.

So yeah, quite a mess, I think the best thing would be to move away from the vectors, but i wouldn't know an different way to do that.

**Comment by MCWertGaming** [comment]
I'll merge this and create a new issue to discuss the merge of of classes together. I think it would probably a good idea to do another call on that topic. If you want to of course.

**Pull request merged**
