### PR TITLE
move tests into tests/

### PR DESCRIPTION
**Pull request by MCWertGaming**
This pull-request moves the testing files inside of the root of the repo into the tests/ folder.

### CODE REVIEW

**Comment by certik** [comment]
The tests are not run properly, I wonder if `enable_tests()` must be in the main file.

**Comment by MCWertGaming** [comment]
yeah, i'm working on this pull-request. And no, enable_testing doesn't need to be there. I have projects were i did this before.

**Comment by MCWertGaming** [comment]
I was wrong about that one, sorry.

**Comment by MCWertGaming** [comment]
Sorry for the many commits... it was a bit hard to me to get what all the files are doing. I tried to make it a bit more clear, like moving `tests.sh` into `ci/` (because it's actually used by the CI). Also i didn't understood that the local directory is '.' instead of './ci'. But well now it's working.

**Comment by MCWertGaming** [comment]
One small note would be the file `build.bat`. It's not used by the project at all. Did you use it for testing purposes? Or what does it do there? I have moved it into tests/ so if it's actually used for testing it's fine I guess. But if you use it for automation, I would suggest to either move it into tools/ or something like that, or you just include it into your external automation instead of in here.

**Comment by MCWertGaming** [comment]
This is now #110

**Pull request closed without merging**
