### PR TITLE
Ci

### PR DESCRIPTION
**Pull request by flagarde**
Add new CI to test many compilers arcg etc... Old one has been kept for now with *_old.yml.
I just activated the c++17 for now but the workflows are ready up to c++20

### CODE REVIEW

**Comment by certik** [comment]
Thanks. There are some CI failures, do you want to either disable the CI or fix the tests?

**Comment by flagarde** [comment]
Some change on the c++ code has to be made, others in dockcroos is because the host is different from the target and I still don't understand how to run on target. Would it be possible to merge it ? We can then go slowly into resolution of errors. I need to make some change on the code and maybe it is better not to mix CI/code changes. But I still need to have all the CI to see all the errors from all compilers etc. Does this is ok for you?

**Comment by certik** [comment]
I would prefer that master always passes at the CI at all times. There are two approaches that you can use:

* Disable the failing tests in this CI, we can polish it and merge; then you reenable them in your next PR where you are trying to fix the issues
* You fix the issues first, to figure out what is needed, we can merge those fixes separately and then merge the full CI

**Comment by flagarde** [comment]
Ok I can first disable the tests part as it not very required for arm* etc that will make some CI pass and I can then do PR for the cases were the build is not passing

**Comment by flagarde** [comment]
For now 52 failing 45 successful

**Comment by flagarde** [comment]
@certik Sorry for the number of commits but most of the changes are trivial so it should be quite fast to dig into the code changes. The most important one is on platform.hpp

It is still needed to check the workflows are compiling with the right standard compiler etc, then it would be fine to suppress old workflows.

The 78 workflows are OK 🎉

**Review by MCWertGaming — APPROVED** [review]

**Comment by flagarde** [comment]
Yes it is ready, then you can go the the C++14 one

**Pull request merged**
