### PR TITLE
Adding dotfiles

### PR DESCRIPTION
**Pull request by MCWertGaming**
This pull-request ties together #76 and #30 by adding the default .gitignore provided by github [here](https://github.com/github/gitignore/blob/master/C%2B%2B.gitignore) and all config files used by visual studio community, visual studio code, Jetbrains CLion and generated files by cmake as standalone.
clang-format will follow as well. The discussing is ongoing in #30.

### CODE REVIEW

**Review by certik — APPROVED** [review]

**Comment by MCWertGaming** [comment]
I have added clang-format. @certik you should check, if the coding style suits your preference. I have done the formating with clang-format in a seperate commit so I can just revert it, if you don't agree with it

**Comment by MCWertGaming** [comment]
What do you think @certik? I have to revert the last commit anyway to fix the merge conflicts

**Comment by certik** [comment]
The formatting looks good, it's very similar to what we already used before.

Let's merge the other PRs first, then we can merge this one.

**Comment by MCWertGaming** [comment]
Yeah, I thought the same coding style is a good thing. Also I really like the chromium coding standards.

**Comment by MCWertGaming** [comment]
I have resolved everything! now we can merge this and proceed with #67.

**Comment by certik** [comment]
Thanks, that looks good. I squashed your commits to make the history a bit tidier.

**Pull request merged**
