### PR TITLE
WIP: Simplify the library

### PR DESCRIPTION
**Pull request by MCWertGaming**
Hello, I'll try to simplify the code of this library in this pull-request. The main changes are turning most inline function into macros, move ansi codes into macros (so everyone can understand what the code actually does, because ansi is not human readable). changing some code logic to be smaller and cleaner. This will take me a bit, so I will post an update if the pull-request is ready to merge! But feel free to add notes, if you notice something i should change.

Best regards,
Damon

### CODE REVIEW

**Comment by certik** [comment]
I think changing functions to macros is not a good idea in C++, because the macros are not part of the `Term` namespace, and so they pollute user's namespace. Rather, we should change all macros to functions.

See, e.g. these guidelines for more background and motivation:

* https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#es31-dont-use-macros-for-constants-or-functions
* https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#es30-dont-use-macros-for-program-text-manipulation
* https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Renum-macro

**Comment by MCWertGaming** [comment]
I think that, if macros are bad due to changing the code to an alias, doing the same with a inline function is basically the same but requires to create objects (like the Term object which is just needed to call is_stdin_a_tty, which is just an inline function). I think that a macro does the same thing but without an object. Or we just create the inline function as anomymous function in the term namespace - would be the same but you don't need to create an object you use only one time. What do you think about that?

**Comment by certik** [comment]
I think we should use either functions in the `Term` namespace, such as `Term::color()`, or have them as static functions in the `Term::Terminal` class, so they can be called as `Term::Terminal::is_stdin_a_tty()` (no object/instance is created, this is a static function called directly from the class). The `color` function is useful even outside of the `Terminal` class, so that's why it was declared outside of it. The `is_stdin_a_tty` seemed to me it makes sense to be part of the `Terminal` class, but it could also be a separate function.

**Comment by MCWertGaming** [comment]
Yeah, i think you are right! I will move the functions to the Term namespace. I would generally minimize the functions of a class. What do you think? Rather all into the namespace or static functions?

I will revert the other definitions as well, sorry of that! I'm rather new to C++.

**Comment by certik** [comment]
No worries. Let's discuss on a case by case basis where a function should belong. It seems more separate functions in the `Term` namespace is the way to go.

**Comment by certik** [comment]
@MCWertGaming do you want to do a video call so that we can talk about the most useful way you can contribute? I have ideas how to improve the library and to add more examples to give people a better idea what it can do.

**Comment by MCWertGaming** [comment]
Sure, which plattform do you prefer? But I can only in the evening on workdays (CEST).

**Comment by certik** [comment]
I sent you a private email to arrange it.

**Comment by MCWertGaming** [comment]
All changes are split into seperate pull-requests.

**Pull request closed without merging**
