### PR TITLE
Move terminal to a dedicated file

### PR DESCRIPTION
**Pull request by flagarde**
Move terminal to a dedicated file and suppress inherance

### CODE REVIEW

**Comment by flagarde** [comment]
@MCWertGaming If this change is ok for you, we can then try to add what as been discussed on #213. This PR would simplify a bit the process

**Review by MCWertGaming — APPROVED** [review]
Yeah, looks about right @flagarde. Thank you for the work. We can merge this when the CI passes. You can add other things as well, but I guess that it would make sense to keep PRs smaller ^^

**Comment by flagarde** [comment]
@MCWertGaming CI passing. Yes sorry too big PR ^^. A bit ugly one I must confess

**Comment by MCWertGaming** [comment]
Really nice, thank you!

**Pull request merged**
