### PR TITLE
Read multi-byte if available

### PR DESCRIPTION
**Pull request by flagarde**
This PR is necessary for a new PR to allow auto-redrawing on resizing terminal. I have tested it on Linux/Windows/MacOS.

@MCWertGaming Please note that if this PR is not passing is because of MacOS ci, it needs to be rerune (I don't have the right to rerun it on this repo).

### CODE REVIEW

**Review by MCWertGaming — APPROVED** [review]
This is really nice, thank you ^^

**Comment by flagarde** [comment]
@MCWertGaming It seems to happen from time to time randomly. Please try to rerun failed workflows and see

**Comment by flagarde** [comment]
@MCWertGaming Sometimes it need to try many times I don't undertand why maybe now g++9 is not available anymore on macos ? I have to check

**Comment by flagarde** [comment]
@MCWertGaming g++9 has been removed but gcc12 has been added I will change the CI for now. Please ignore this error for now

**Comment by MCWertGaming** [comment]
Alright, we'll merge it then, thanks!

**Pull request merged**
