### PR TITLE
removed the get_term_size_slow() function

### PR DESCRIPTION
**Pull request by MCWertGaming**
this removes the  get_term_size_slow() function. We have already talked about that, I just wasn't sure if its needed. I mean like we have get_term_size(), wich is the same function but fast. But like I said, this is optional. I understand if we are keeping this for fall-back purposes.

### CODE REVIEW

**Comment by certik** [comment]
Let's this PR open for a while. I want to do a thorough testing first on all platforms. We should enumerate the platforms we test and ensure things work everywhere (#73) before removing this.

**Comment by MCWertGaming** [comment]
Sounds great!

**Comment by MCWertGaming** [comment]
@certik do we wan't to merge this before #67? If not, I'll just close the pull-request and change it into an issue. We can do this later on then.

**Comment by certik** [comment]
Let's change this into an issue.

**Pull request closed without merging**
