### PR TITLE
Window class update

### LINKED ISSUE #128: Unify Window and Window_24bit
We have to unify the color type as follows:
```diff
diff --git a/cpp-terminal/terminal.cpp b/cpp-terminal/terminal.cpp
index 69a303f..ff076b8 100644
--- a/cpp-terminal/terminal.cpp
+++ b/cpp-terminal/terminal.cpp
@@ -624,6 +624,13 @@ void Term::Window_24bit::clear() {
 }
 
 bool Term::Window_24bit::rgb_equal(rgb& rgb_one, rgb rgb_two) {
+    if (rgb_two.color_type == rgb::type_basic) {
+        std::cout << rgb_two.color_type_union.basic << std::endl;
+    } else {
+        std::cout << rgb_two.color_type_union.rgb.r << std::endl;
+        std::cout << rgb_two.color_type_union.rgb.g << std::endl;
+        std::cout << rgb_two.color_type_union.rgb.b << std::endl;
+    }
     return rgb_one.r == rgb_two.r && rgb_one.b == rgb_two.b &&
            rgb_one.g == rgb_two.g;
 }
diff --git a/cpp-terminal/terminal.h b/cpp-terminal/terminal.h
index a7b384c..c0e4999 100644
--- a/cpp-terminal/terminal.h
+++ b/cpp-terminal/terminal.h
@@ -196,6 +196,33 @@ class Window_24bit {
     std::vector<char32_t> chars;  // the characters in row first order
     struct rgb {
         unsigned int r, g, b;
+        enum ColorType {
+            type_rgb, type_basic
+        } color_type;
+        union ColorTypeUnion {
+            struct {
+                unsigned int r, g, b;
+            } rgb;
+            enum BasicColors {
+                black = 30,
+                red = 31,
+                green = 32,
+                yellow = 33,
+                blue = 34,
+                magenta = 35,
+                cyan = 36,
+                white = 37,
+                reset = 39,
+                gray = 90,
+                bright_red = 91,
+                bright_green = 92,
+                bright_yellow = 93,
+                bright_blue = 94,
+                bright_magenta = 95,
+                bright_cyan = 96,
+                bright_white = 97
+            } basic;
+        } color_type_union;
     };
     std::vector<rgb> m_fg;
     std::vector<rgb> m_bg;
```

This provides an example how to declare it and how to access it.

### PR DESCRIPTION
**Pull request by MCWertGaming**
This PR updates the window class to handle 24bit / 8bit and 4bit colors in one implementation.

Fixes #128, #96, #107.

WIP: #108.

### CODE REVIEW

**Comment by flagarde** [comment]
Does this is superseded by your new PR?

**Comment by MCWertGaming** [comment]
Well #191 implements #190, which isn't covered by this PR, but the whole auto color stuff comes from this PR.

The reason was that this PR gotten a bit over my head, so I rather split it into smaller things so the window class update can be easily merged without having a big mess of different color functions and everything.

So the plan is:
- Merge #191
- Apply the new Color functions into a unified Window class version (Currently there is one window class for 4bit and one for 24bit, while the 24bit class doesn't work on macos due to lack of support)
- Update the 24bit example to use the auto color function
- Probably also a cleanup and upgrading the Prompt to 24bit colors as well
- Also the platform header should be pruned and simplified.

**Comment by flagarde** [comment]
@MCWertGaming does this PR should be closed ? The platform header should be pruned and simplified. could be solved in other PR (maybe creating an issue for this)

**Comment by MCWertGaming** [comment]
Yeah I moved it into #213.

**Pull request closed without merging**
