### PR TITLE
update readme

### PR DESCRIPTION
**Pull request by MCWertGaming**
This PR updates the readme to include the change to new source files. I have also improved some texts and moved the documentation to the wiki on github.

TODO:
- [ ] Finish moving the documentation to the wiki
- [ ] Finish the setup instructions page in the wiki

### CODE REVIEW

**Comment by MCWertGaming** [comment]
@certik Would be nice if you could give some feedback. your can preview the rendered markdown here
https://github.com/MCWertGaming/cpp-terminal/blob/readme/README.md.

**Comment by MCWertGaming** [comment]
@certik what do you think about this readme improvement? I tried to make it more fancy with some markdown styling and a header image

**Comment by MCWertGaming** [comment]
@certik what about this PR?

**Review by certik — APPROVED** [review]
I think this is fine. I don't have time right now to review and test everything carefully. I think it's good if you can take over the maintenance. So I'll review based on if I see any big red flags, which I don't in this case so good to go in.

**Comment by MCWertGaming** [comment]
Sure! I'll do my best.

**Pull request merged**
