### PR TITLE
Splitting the rest

### PR DESCRIPTION
**Pull request by MCWertGaming**
This PR splits the missing headers into source files and finally removes `base_terminal.h` and `terminal.h`.

### CODE REVIEW

**Comment by MCWertGaming** [comment]
The changes are done now. Just have to test the library on windows. @certik could you test the example programs meanwhile on macos? The input would be the most important thing to test.

**Comment by wolfv** [comment]
I just tested a bit on macOS. The only issue I could find is that the prompt example, trying to add a new line with ALT+Enter ends the program with `Runtime error: Invalid byte in UTF8 encoded string`

**Comment by MCWertGaming** [comment]
I have seen that too, but that was like this before. Also it's only after a few new lines - or is it directly causing a runtime error for you?

**Comment by certik** [comment]
The Alt-Enter has to be fixed, but that already happens in master:
```
(lf) repos/cpp-terminal(master) $ ./examples/prompt 
Interactive prompt.
  * Use Ctrl-D to exit.
  * Use Enter to submit.
  * Features:
    - Editing (Keys: Left, Right, Home, End, Backspace)
    - History (Keys: Up, Down)
    - Multi-line editing (use Alt-Enter to add a new line)
> 4                                                                      1,2   ]
Submitted text: 4

> 4+4                                                                    1,4   ]
Submitted text: 4+4

> Unknown error.                                                         1,1   ]
(lf) repos/cpp-terminal(master) $ ./examples/prompt
Interactive prompt.
  * Use Ctrl-D to exit.
  * Use Enter to submit.
  * Features:
    - Editing (Keys: Left, Right, Home, End, Backspace)
    - History (Keys: Up, Down)
    - Multi-line editing (use Alt-Enter to add a new line)
> Unknown error.                                                         1,1   ]
```
So it is unrelated to this PR.

**Comment by certik** [comment]
This PR compiles fine and seem to work on Apple M1.

However, the prompt example now starts in an empty screen. The behavior it should do is to start in the user terminal, like before. The full screen mode is tested by other examples such as `menu` or `menu_screen`, so let's use the `prompt` to test that it works in a regular terminal.

**Comment by MCWertGaming** [comment]
I'll fix the empty screen for the prompt example quickly. WIndows works fine!

**Comment by MCWertGaming** [comment]
@certik the prompt is broken on windows. But in the master branch as well. That must be fixed as well.

On runtime, I get the error: 

Debug Assertion Failed!
Expression: c >= -1 && c <= 255

in file minkernel/crts/ucrt/src/appcrt/convert/jsctype.cpp

**Comment by MCWertGaming** [comment]
Also the reloading of the old screen is a bit broken somehow on windows. Will create Issues on those.

**Comment by MCWertGaming** [comment]
I have created issues on the found problems. Once the unit tests continue, you should look one last tme over the changes and once you approve this PR, I'll merge.

**Review by certik — APPROVED** [review]
The prompt now works. I think this is good to merge as is.

Then we need to fix all bugs, on Windows as well as the alt-enter on a mac.

**Pull request merged**
