### PR TITLE
added codeql analysis workflow

### PR DESCRIPTION
**Pull request by MCWertGaming**
This pull-request adds the in #77 requested codeql scanning for avoiding misstakes, others did already.

### CODE REVIEW

**Comment by certik** [comment]
Where is the output supposed to be to check that this works? You main need to rename `main` to `master`.

**Comment by MCWertGaming** [comment]
Oh right, sorry. My repos have all "main" as main branch, because github changed it from master to main due to political correctness.

**Comment by certik** [comment]
Looks like here are some warnings (turned into errors). Go ahead and try to fix them.

**Comment by MCWertGaming** [comment]
It's funny. Seems like CodeQL is enabling more compiler warnings than my changes.
```
/home/runner/work/cpp-terminal/cpp-terminal/examples/menu_window.cpp:55:52: error: ‘cols’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
     55 |                 case Key::ARROW_RIGHT: if (w < cols-5) w++; break;
        |                                                ~~~~^~
```
I'll fix that soon.

**Comment by certik** [comment]
Looks like there is another such issue. Btw, I thought I had warnings enabled. What we should do is enable all warnings and turn then into errors on the CI. I guess I didn't, just found the issue for exactly this: https://github.com/jupyter-xeus/cpp-terminal/issues/33

**Comment by MCWertGaming** [comment]
yeah sure, but warning with C++ compilers are not that easy. I have added some too, like -Wall -Wextra etc. That's why I wanted to seperate the header files from the source in the first place. With a compile target, you can just enable the warning on the target itself instead of programms that are using it.

**Review by certik — APPROVED** [review]
This looks great, thank you!

**Pull request merged**
